config/routes.rb
SampleJs::Application.routes.draw do

  root 'posts#index'
	resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :load

	def load
		all_posts
		@post = Post.new
	end

	respond_to :js, :html
  def index
		all_posts
		respond_with
  end

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(post_params)
		all_posts
		if @post.save
			respond_with
		else
			redirect_to posts_path
		end
	end
		
	def edit
		@post = Post.find(params[:id])
		respond_with
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			all_posts
			respond_with
		else
		end
	end

	def show
		@post = Post.find(params[:id])
		all_posts
		respond_with
	end

	def destroy
		@post = Post.find(params[:id])
		@post.delete
		respond_with
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end

	def all_posts
		@posts = Post.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SampleJs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">SampleJs</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9 well" style="background-color:red;">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post, :remote => true) do |f| %>
<%=  f.text_field :title %>
<br />
<%=  f.text_field :body %>
<br />
<%= f.submit %>
<%= f.button "reset", type: "reset" %>
<% end %>

app/views/posts/_posts.html.erb
<table class="table table-stripped">
	<tr>
		<th>
			Title
		</th>
		<th>
			Content
		</th>
		<th></th>
	</tr>
	<% @posts.each do |post| %>
		<tr>
			<td>
				<%= post.title %>
			</td>
			<td>
				<%= post.body %>
			</td>
			<td>
				<%= link_to 'show', post_path(post), remote: true %>
				<%= link_to 'Edit', edit_post_path(post), remote: true %>
				<%= link_to 'Destroy', post, method: :delete, remote: true %>
			</td>
		</tr>
	<% end %>
</table>

	

app/views/posts/create.js.erb
$('#posts_list').html('<%= j render('posts') %>')
$(":input:not(input[type=submit])").val("");

app/views/posts/destroy.js.erb
$('#posts_list').html('<%= j render('posts')  %>')

app/views/posts/edit.js.erb
$('#posts_form').html('<%= j render('form') %>');

app/views/posts/index.html.erb
<h1> MY POSTS </h1>

<div id='display_post'></div>

<div id="posts_form">
	<%= render "form" %>
</div>

<div id="posts_list">
	<%= render "posts" %>
</div>

app/views/posts/show.js.erb
$('#display_post').html('<%= @post.title << " " << @post.body  %>');

app/views/posts/update.js.erb
$('#posts_list').html('<%= j render('posts') %>');

$(":input:not(input[type=submit])").val("");